defmodule GroceryPlanner.Repo.Migrations.CreateNotificationPreferences do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notification_preferences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "notification_preferences_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "notification_preferences_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :expiration_alerts_enabled, :boolean, default: true
      add :expiration_alert_days, :bigint, default: 7
      add :recipe_suggestions_enabled, :boolean, default: true
      add :email_notifications_enabled, :boolean, default: false
      add :in_app_notifications_enabled, :boolean, default: true

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:notification_preferences, "notification_preferences_user_id_fkey")

    drop constraint(:notification_preferences, "notification_preferences_account_id_fkey")

    drop table(:notification_preferences)
  end
end
