defmodule GroceryPlanner.Repo.Migrations.AddShoppingLists do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shopping_lists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false, default: "Shopping List"
      add :status, :text, default: "active"
      add :generated_from, :text, default: "manual"
      add :generated_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :notes, :text

      add :account_id,
          references(:accounts,
            column: :id,
            name: "shopping_lists_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:shopping_list_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :quantity, :decimal, default: "1"
      add :unit, :text
      add :checked, :boolean, default: false
      add :checked_at, :utc_datetime
      add :price, :money_with_currency
      add :notes, :text

      add :shopping_list_id,
          references(:shopping_lists,
            column: :id,
            name: "shopping_list_items_shopping_list_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :grocery_item_id,
          references(:grocery_items,
            column: :id,
            name: "shopping_list_items_grocery_item_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :account_id,
          references(:accounts,
            column: :id,
            name: "shopping_list_items_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:shopping_list_items, "shopping_list_items_shopping_list_id_fkey")

    drop constraint(:shopping_list_items, "shopping_list_items_grocery_item_id_fkey")

    drop constraint(:shopping_list_items, "shopping_list_items_account_id_fkey")

    drop table(:shopping_list_items)

    drop constraint(:shopping_lists, "shopping_lists_account_id_fkey")

    drop table(:shopping_lists)
  end
end
