defmodule GroceryPlanner.Repo.Migrations.AddGroceryItemTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:grocery_item_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :color, :text, default: "#3B82F6"
      add :description, :text

      add :account_id,
          references(:accounts,
            column: :id,
            name: "grocery_item_tags_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:grocery_item_tags, [:account_id, :name],
             name: "grocery_item_tags_unique_name_per_account_index"
           )

    create table(:grocery_item_taggings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :grocery_item_id,
          references(:grocery_items,
            column: :id,
            name: "grocery_item_taggings_grocery_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:grocery_item_tags,
            column: :id,
            name: "grocery_item_taggings_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:grocery_item_taggings, [:grocery_item_id, :tag_id],
             name: "grocery_item_taggings_unique_grocery_item_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:grocery_item_taggings, [:grocery_item_id, :tag_id],
                     name: "grocery_item_taggings_unique_grocery_item_tag_index"
                   )

    drop constraint(:grocery_item_taggings, "grocery_item_taggings_grocery_item_id_fkey")

    drop constraint(:grocery_item_taggings, "grocery_item_taggings_tag_id_fkey")

    drop table(:grocery_item_taggings)

    drop_if_exists unique_index(:grocery_item_tags, [:account_id, :name],
                     name: "grocery_item_tags_unique_name_per_account_index"
                   )

    drop constraint(:grocery_item_tags, "grocery_item_tags_account_id_fkey")

    drop table(:grocery_item_tags)
  end
end
