defmodule GroceryPlanner.Repo.Migrations.CreateRecipeTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:recipes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :instructions, :text
      add :prep_time_minutes, :bigint
      add :cook_time_minutes, :bigint
      add :servings, :bigint, default: 4
      add :difficulty, :text, default: "medium"
      add :image_url, :text
      add :source, :text
      add :is_favorite, :boolean, default: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "recipes_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:recipe_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :color, :text, default: "#3B82F6"

      add :account_id,
          references(:accounts,
            column: :id,
            name: "recipe_tags_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:recipe_tags, [:account_id, :name],
             name: "recipe_tags_unique_name_per_account_index"
           )

    create table(:recipe_taggings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_taggings_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :tag_id,
          references(:recipe_tags,
            column: :id,
            name: "recipe_taggings_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:recipe_taggings, [:recipe_id, :tag_id],
             name: "recipe_taggings_unique_recipe_tag_index"
           )

    create table(:recipe_ingredients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :unit, :text
      add :is_optional, :boolean, default: false
      add :substitution_notes, :text
      add :preparation, :text
      add :sort_order, :bigint, default: 0

      add :account_id,
          references(:accounts,
            column: :id,
            name: "recipe_ingredients_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_ingredients_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :grocery_item_id,
          references(:grocery_items,
            column: :id,
            name: "recipe_ingredients_grocery_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:recipe_ingredients, "recipe_ingredients_account_id_fkey")

    drop constraint(:recipe_ingredients, "recipe_ingredients_recipe_id_fkey")

    drop constraint(:recipe_ingredients, "recipe_ingredients_grocery_item_id_fkey")

    drop table(:recipe_ingredients)

    drop_if_exists unique_index(:recipe_taggings, [:recipe_id, :tag_id],
                     name: "recipe_taggings_unique_recipe_tag_index"
                   )

    drop constraint(:recipe_taggings, "recipe_taggings_recipe_id_fkey")

    drop constraint(:recipe_taggings, "recipe_taggings_tag_id_fkey")

    drop table(:recipe_taggings)

    drop_if_exists unique_index(:recipe_tags, [:account_id, :name],
                     name: "recipe_tags_unique_name_per_account_index"
                   )

    drop constraint(:recipe_tags, "recipe_tags_account_id_fkey")

    drop table(:recipe_tags)

    drop constraint(:recipes, "recipes_account_id_fkey")

    drop table(:recipes)
  end
end
