defmodule GroceryPlanner.Repo.Migrations.Inventory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:storage_locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :temperature_zone, :text

      add :account_id,
          references(:accounts,
            column: :id,
            name: "storage_locations_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:storage_locations, [:account_id, :name],
             name: "storage_locations_unique_name_per_account_index"
           )

    create table(:inventory_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :unit, :text
      add :purchase_price, :money_with_currency
      add :purchase_date, :date
      add :use_by_date, :date
      add :notes, :text
      add :status, :text, default: "available"

      add :account_id,
          references(:accounts,
            column: :id,
            name: "inventory_entries_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :grocery_item_id, :uuid, null: false
      add :storage_location_id, :uuid

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:grocery_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inventory_entries) do
      modify :grocery_item_id,
             references(:grocery_items,
               column: :id,
               name: "inventory_entries_grocery_item_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :storage_location_id,
             references(:storage_locations,
               column: :id,
               name: "inventory_entries_storage_location_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:grocery_items) do
      add :name, :text, null: false
      add :description, :text
      add :default_unit, :text
      add :barcode, :text

      add :account_id,
          references(:accounts,
            column: :id,
            name: "grocery_items_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :category_id, :uuid

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:grocery_items) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "grocery_items_category_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:categories) do
      add :name, :text, null: false
      add :icon, :text
      add :sort_order, :bigint, default: 0

      add :account_id,
          references(:accounts,
            column: :id,
            name: "categories_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:categories, [:account_id, :name],
             name: "categories_unique_name_per_account_index"
           )
  end

  def down do
    drop_if_exists unique_index(:categories, [:account_id, :name],
                     name: "categories_unique_name_per_account_index"
                   )

    drop constraint(:categories, "categories_account_id_fkey")

    alter table(:categories) do
      remove :updated_at
      remove :created_at
      remove :account_id
      remove :sort_order
      remove :icon
      remove :name
    end

    drop constraint(:grocery_items, "grocery_items_category_id_fkey")

    alter table(:grocery_items) do
      modify :category_id, :uuid
    end

    drop table(:categories)

    drop constraint(:grocery_items, "grocery_items_account_id_fkey")

    alter table(:grocery_items) do
      remove :updated_at
      remove :created_at
      remove :category_id
      remove :account_id
      remove :barcode
      remove :default_unit
      remove :description
      remove :name
    end

    drop constraint(:inventory_entries, "inventory_entries_grocery_item_id_fkey")

    drop constraint(:inventory_entries, "inventory_entries_storage_location_id_fkey")

    alter table(:inventory_entries) do
      modify :storage_location_id, :uuid
      modify :grocery_item_id, :uuid
    end

    drop table(:grocery_items)

    drop constraint(:inventory_entries, "inventory_entries_account_id_fkey")

    drop table(:inventory_entries)

    drop_if_exists unique_index(:storage_locations, [:account_id, :name],
                     name: "storage_locations_unique_name_per_account_index"
                   )

    drop constraint(:storage_locations, "storage_locations_account_id_fkey")

    drop table(:storage_locations)
  end
end
