defmodule GroceryPlanner.Repo.Migrations.Phase11WasteTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:usage_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :decimal, null: false
      add :unit, :text
      add :reason, :text, null: false

      add :occurred_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :cost, :money_with_currency

      add :account_id,
          references(:accounts,
            column: :id,
            name: "usage_logs_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :grocery_item_id,
          references(:grocery_items,
            column: :id,
            name: "usage_logs_grocery_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:usage_logs, "usage_logs_account_id_fkey")

    drop constraint(:usage_logs, "usage_logs_grocery_item_id_fkey")

    drop table(:usage_logs)
  end
end
