defmodule GroceryPlanner.Repo.Migrations.AddMealPlanning do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:meal_plans, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :scheduled_date, :date, null: false
      add :meal_type, :text, null: false
      add :servings, :bigint, default: 4
      add :notes, :text
      add :status, :text, default: "planned"
      add :completed_at, :utc_datetime

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "meal_plans_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "meal_plans_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:meal_plan_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :is_active, :boolean, default: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "meal_plan_templates_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:meal_plan_template_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :day_of_week, :bigint, null: false
      add :meal_type, :text, null: false
      add :servings, :bigint, default: 4

      add :template_id,
          references(:meal_plan_templates,
            column: :id,
            name: "meal_plan_template_entries_template_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "meal_plan_template_entries_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "meal_plan_template_entries_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:meal_plan_template_entries, "meal_plan_template_entries_template_id_fkey")

    drop constraint(:meal_plan_template_entries, "meal_plan_template_entries_recipe_id_fkey")

    drop constraint(:meal_plan_template_entries, "meal_plan_template_entries_account_id_fkey")

    drop table(:meal_plan_template_entries)

    drop constraint(:meal_plan_templates, "meal_plan_templates_account_id_fkey")

    drop table(:meal_plan_templates)

    drop constraint(:meal_plans, "meal_plans_recipe_id_fkey")

    drop constraint(:meal_plans, "meal_plans_account_id_fkey")

    drop table(:meal_plans)
  end
end
