defmodule GroceryPlanner.Repo.Migrations.AllowNilRecipeIngredientQuantity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:recipe_ingredients) do
      modify :quantity, :decimal, null: true
    end
  end

  def down do
    alter table(:recipe_ingredients) do
      modify :quantity, :decimal, null: false
    end
  end
end
