defmodule GroceryPlanner.Repo.Migrations.AddRecipeChainingAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:recipes) do
      add :is_base_recipe, :boolean, default: false
      add :is_follow_up, :boolean, default: false

      add :parent_recipe_id,
          references(:recipes,
            column: :id,
            name: "recipes_parent_recipe_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:recipe_ingredients) do
      add :usage_type, :text, default: "fresh"
    end
  end

  def down do
    alter table(:recipe_ingredients) do
      remove :usage_type
    end

    drop constraint(:recipes, "recipes_parent_recipe_id_fkey")

    alter table(:recipes) do
      remove :parent_recipe_id
      remove :is_follow_up
      remove :is_base_recipe
    end
  end
end
