defmodule GroceryPlanner.Repo.Migrations.AddReceipts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :image_path, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :job_id, :text
      add :merchant, :text
      add :total_amount, :decimal
      add :scanned_date, :date
      add :items, {:array, :map}, default: []

      add :account_id,
          references(:accounts,
            column: :id,
            name: "receipts_account_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:receipts, "receipts_account_id_fkey")

    drop table(:receipts)
  end
end
