defmodule GroceryPlanner.Repo.Migrations.AddFamilyMembersAndPreferences do
  @moduledoc """
  Adds family_members and recipe_preferences tables.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  and manually trimmed to remove snapshot drift from unrelated resources.
  """

  use Ecto.Migration

  def up do
    create table(:family_members, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :account_id,
          references(:accounts, column: :id, name: "family_members_account_id_fkey", type: :uuid),
          null: false

      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:recipe_preferences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :preference, :text, null: false

      add :account_id,
          references(:accounts,
            column: :id,
            name: "recipe_preferences_account_id_fkey",
            type: :uuid
          ),
          null: false

      add :family_member_id,
          references(:family_members,
            column: :id,
            name: "recipe_preferences_family_member_id_fkey",
            type: :uuid
          ),
          null: false

      add :recipe_id,
          references(:recipes,
            column: :id,
            name: "recipe_preferences_recipe_id_fkey",
            type: :uuid
          ),
          null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:recipe_preferences, [:account_id, :family_member_id, :recipe_id],
             name: "recipe_preferences_unique_member_recipe_index"
           )
  end

  def down do
    drop_if_exists unique_index(:recipe_preferences, [:account_id, :family_member_id, :recipe_id],
                     name: "recipe_preferences_unique_member_recipe_index"
                   )

    drop constraint(:recipe_preferences, "recipe_preferences_account_id_fkey")
    drop constraint(:recipe_preferences, "recipe_preferences_family_member_id_fkey")
    drop constraint(:recipe_preferences, "recipe_preferences_recipe_id_fkey")
    drop table(:recipe_preferences)

    drop constraint(:family_members, "family_members_account_id_fkey")
    drop table(:family_members)
  end
end
