defmodule GroceryPlanner.Repo.Migrations.AddCuisineAndDietaryNeedsToRecipes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:recipes) do
      add :cuisine, :text
      add :dietary_needs, {:array, :text}, default: []
    end
  end

  def down do
    alter table(:recipes) do
      remove :dietary_needs
      remove :cuisine
    end
  end
end
