defmodule GroceryPlanner.Repo.Migrations.AddWasteReductionAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:recipes) do
      add :freezable, :boolean, default: false
      add :preservation_tip, :text
      add :waste_reduction_tip, :text
    end

    alter table(:grocery_items) do
      add :is_waste_risk, :boolean, default: false
    end
  end

  def down do
    alter table(:grocery_items) do
      remove :is_waste_risk
    end

    alter table(:recipes) do
      remove :waste_reduction_tip
      remove :preservation_tip
      remove :freezable
    end
  end
end
