defmodule GroceryPlanner.Repo.Migrations.AddMealPlannerLayoutToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :meal_planner_layout, :text, null: false, default: "explorer"
    end
  end

  def down do
    alter table(:users) do
      remove :meal_planner_layout
    end
  end
end
